apiVersion: v1
kind: ConfigMap
metadata:
  name: eventbooking-config
  namespace: onlineeventbooking-yourname
data:
  USER_DB_HOST: "postgres-svc.onlineeventbooking-yourname.svc.cluster.local"
  USER_DB_NAME: "user_db"

  BOOKING_DB_HOST: "postgres-svc.onlineeventbooking-yourname.svc.cluster.local"
  BOOKING_DB_NAME: "booking_db"

  EVENT_DB_URI: "mongodb://mongo-svc.onlineeventbooking-yourname.svc.cluster.local:27017/eventdb"
  NOTIFICATION_DB_URI: "mongodb://mongo-svc.onlineeventbooking-yourname.svc.cluster.local:27017/notificationsdb"

  EVENT_SERVICE_URL: "http://event-service-svc:4000"
  # etc. any other service-to-service URLs
