apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service-depl
  namespace: onlineeventbooking-yourname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service-container
        image: your-dockerhub-username/frontend-service:latest
        ports:
          - containerPort: 80
        # If you have environment variables for API endpoints, set them here
        env:
        - name: REACT_APP_USER_API
          value: "http://user-service-svc:3001"
        - name: REACT_APP_EVENT_API
          value: "http://event-service-svc:4000"
        - name: REACT_APP_BOOKING_API
          value: "http://booking-service-svc:5000"
        - name: REACT_APP_NOTIFICATION_API
          value: "http://notification-service-svc:6060"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-svc
  namespace: onlineeventbooking-yourname
spec:
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
